---
- name: Build Instance  
  hosts: localhost  
  tasks:
    - name: "Include the cornerstone role to create aws instances"
      include_role:
        name: ../roles/ansible-role-cornerstone

- name: "Operating system tasks"
  hosts: Openshift
  tasks:
    - name: "Include the Register to Red Hat role"
      include_role:
        name: ../roles/ansible-role-redhat-register

- name: "Operating system tasks"
  hosts: Openshift
  tasks:
    - name: "Include the role to do ocp prereqs"
      include_role:
        name: ../roles/ansible-role-ocp-prereqs
