---

- name: Build VMs Ready for use 
  hosts: localhost
  tasks:
    - include_role:
        name: ../roles/ansible-role-cornerstone

- name: Configure Operating systems
  hosts: satellite
  tasks:
    - include_role:
        name: ../roles/ansible-role-redhat-register

  # NEED to add mount/disk configuration for satellite at some point.

- name: Install Satellite
  hosts: satellite
  become: true
  tasks:
    - include_role:
        name: ../roles/ansible-role-satellite-cultivator

